language: node_js
node_js:
  - "stable"
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
  - npm install -g @angular/cli
script:
- ng lint
- ng build --prod --base-href https://AgnieszkaKurek.github.io/TicTacToeGameAngular/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: 79618ffee94d75b298dd65c9ccd6fb6bbc7c05db
  local_dir: dist/TouristGuide
  on:
    branch: master